# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 422b543258564334a688a806fe88a313374c756146710cf7fca58c6a54342bbbda29aed82b207cac0e19904f282aae198cc90f1d45ddaa5f52de30d76ec5f2d6

test:
  secret_key_base: 928b55aba4d48a22d47b58b20a899a02945babfaddaddc433a2cffbeac4e125b61d1ae25d4ba02d7cd29f34ba81b4763e21450eb6092e0b9623586f41a4a6215

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
